---
kind: pipeline
type: kubernetes
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:


- name: tags
  image: bitnami/git  # https://hub.docker.com/r/bitnami/git/
  commands:
  - git fetch --tags
  - echo "${DRONE_COMMIT_BRANCH/\//-}-$(git describe --tags --always --dirty),${DRONE_COMMIT_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8},latest" > .tags

- name: build
  image: golang:1.10
  commands:
  - cd posix
  - tar -xf fixtures.tar -C /
  - go test -v

- name: docker-publish
  image: plugins/ecr
  settings:
    access_key:
      from_secret: ecr_id
    create_repository: true
    dockerfile: docker/Dockerfile.linux.amd64
    region: eu-west-2
    registry: 976217792753.dkr.ecr.eu-west-2.amazonaws.com
    repo: ${CI_REPO}
    secret_key:
      from_secret: ecr_key

trigger:
  branch:
  - master
  # - develop
  # - feature/*
  event:
  - push
  # - pull_request
  # - tag



